### ISSUE TITLE
Ensure elasticsearch is installed

### ISSUE THREAD

**Issue by n1te1337** [waawal/vagrant-elasticsearch#3]
Hey, I get the following error when running `vagrant up`

```
TASK: [elasticsearch | Ensure elasticsearch is installed] *********************
failed: [default] => (item=openjdk-7-jre-headless,elasticsearch) => {"failed": true, "item": "openjdk-7-jre-headless,elasticsearch", "parsed": false}
invalid output was: SUDO-SUCCESS-oewznrdtwailipuspaqahtnncvrhielr
```

 any ideas?

**Comment by waawal** [comment]
Hi @n1te1337 
I'm unable to reproduce this on  `Vagrant 1.6.2` with `ansible 1.6.1`.
Maybe this issue could be related to this bug: https://github.com/ansible/ansible/issues/5533

If not, are you running the precise64 box that is reffered to in the the `Vagrantfile`?

**Comment by n1te1337** [comment]
@waawal got it working, it was the vagrant box after all. Thanks
